routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    dd('salom');
    $about_left=\App\Models\About_left::find(1);
    $about_right=\App\Models\About_right::find(1);
    $card=\App\Models\Cards::all();
    $contact=\App\Models\Contact::find(1);
    $home=\App\Models\Home::find(1);
    $intro=\App\Models\Introduction::find(1);
    $message=\App\Models\Message::find(1);
    $more=\App\Models\More::all();
    $part=\App\Models\Participants::all();
    $portfolio=DB::select('SELECT p.*,pc.name as category from portfolio p JOIN portfolio_category pc on p.cat_id=pc.id');
    $pricing=\App\Models\Pricing::all();
    $service=\App\Models\Service::all();
    $service_card=\App\Models\Service_card::all();
    $teacher=\App\Models\Teachers::all();

    return view('samo.index.index', compact(

        'about_left', 'about_right','card',
        'contact','home','intro','message','more','part','portfolio',
        'pricing','service','service_card','teacher'

    ));
})->name('samo.home');
Route::get('admin', function () {
    return view('admin.layouts.app');
});
Route::middleware(['auth'])->group(function () {
    Route::resource('about_left',\App\Http\Controllers\About_leftController::class);
    Route::resource('about_right',\App\Http\Controllers\About_rightController::class);
    Route::resource('blog',\App\Http\Controllers\BlogController::class);
    Route::resource('message',\App\Http\Controllers\MessageController::class);
    Route::resource('more',\App\Http\Controllers\MoreController::class);
    Route::resource('portfolio',\App\Http\Controllers\PortfolioController::class);
    Route::resource('pricing',\App\Http\Controllers\PricingController::class);
    Route::resource('cards',\App\Http\Controllers\CardsController::class);
    Route::resource('contact',\App\Http\Controllers\ContactController::class);
    Route::resource('home_main',\App\Http\Controllers\HomeMainController::class);
    Route::resource('introduction',\App\Http\Controllers\IntroductionController::class);
    Route::resource('participants',\App\Http\Controllers\ParticipantsController::class);
    Route::resource('service',\App\Http\Controllers\ServiceController::class);
    Route::resource('service_card',\App\Http\Controllers\Service_cardController::class);
    Route::resource('teachers',\App\Http\Controllers\TeachersController::class);
    Route::resource('count', \App\Http\Controllers\BlogController::class);

});
Route::resource('admin_data', \App\Http\Controllers\About_rightController::class);
Route::resource('sendmessage', \App\Http\Controllers\Message_sendController::class);




Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);



//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home.index');

app/Models/Cards.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cards extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'cards';
    protected $fillable = [

        'id',
        'image',
        'text',
        'link'

    ];
}

app/Http/Controllers/CardsController.php
<?php

namespace App\Http\Controllers;

use App\Models\About_left;
use App\Models\Cards;
use Illuminate\Http\Request;

class CardsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cards=Cards::all();
        return view('admin.pages.cards.index', compact('cards'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'text'=>'required',
            'image'=>'required',
            'link'=>'required'

        ]);

        $item= new Cards();
        $item->text=$request->text;
        $item->link=$request->link;

        $imageName = time().'.'.$request->file('image')->getClientOriginalExtension();
        $request->file('image')->storeAs('public/images/', $imageName);
        $item->image=$imageName;

        $item->save();
        return redirect()->route('cards.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'text'=>'required',
        ]);

        $update=Cards::find($id);
        $update->text=$request->text;
        $update->link=$request->link;
        if ($request->file('image')){
            $imageName = time().'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/images/', $imageName);
            if (file_exists(public_path('storage/images/'.$update->image))){
                @unlink(public_path('storage/images/'.$update->image));
            }
            $update->image=$imageName;
        }

        $update->update();
        return redirect()->route('cards.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete=Cards::find($id);
        $delete->delete();
        return redirect()->route('cards.index');
    }
}

resources/views/admin/pages/cards/index.blade.php
@extends('admin.layouts.app')


@section('main')

    <div class="row">
        <h2 class="text-center col-6">Card Sozlamalari</h2>
        <div class="col-6">
            <div class="text-end">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#create" data-bs-whatever="@getbootstrap">Card qo'shish</button>

            </div>
            <div class="modal fade" id="create" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Card</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{route('cards.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                @method('post')
                                <div class="mb-3">
                                    <label for="header_text" class="col-form-label">Yozuvmi Kiriting</label>
                                    <input name="text" type="text" class="form-control">

                                    <label for="img" class="col-form-label">Suratni Kiriting</label>
                                    <input name="image" type="file" class="form-control">

                                    <label for="link" class="col-form-label">Kartning linki</label>
                                    <input name="link" type="text" class="form-control">

                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                                    <button type="submit" class="btn btn-primary">Tasdiqlash</button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

   <div class="row">
       <div class="">
           <div class="container position-relative">
               <div class="row gy-4 mt-5">
                   @foreach($cards as $card)
                   <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="100">
                       <div >
                           <div>
                               <img src="{{ asset('public/storage/images/'.$card->image)  }}" alt="{{ $card->image }}" class="img-fluid rounded-4 mb-4 w-10">
                           </div>
                           <div class="">

                               <h4 class="title"><a>Assosiy Yozuv: {{$card->text}}</a></h4>
                           </div>
                       </div>


                      <div class="d-flex justify-content-between">

{{--                          Update--}}
                          <div class="">
                              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#update{{$card->id}}" data-bs-whatever="@getbootstrap">Card Tahrirlash</button>
                          </div>
                          <div class="modal fade" id="update{{$card->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                  <div class="modal-content">
                                      <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Card</h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                      </div>
                                      <div class="modal-body">
                                          <form action="{{route('cards.update', $card->id)}}" method="post" enctype="multipart/form-data">
                                              @csrf
                                              @method('put')
                                              <div class="mb-3">
                                                  <label for="header_text" class="col-form-label">Yozuvmi Ozgartirish</label>
                                                  <input name="text" type="text" class="form-control" value="{{$card->text}}">

                                                  <label for="img" class="col-form-label">Suratni Ozgartirish</label>
                                                  <input name="image" type="file" class="form-control" value="{{$card->image}}">

                                                  <label for="link" class="col-form-label">Kartning link</label>
                                                  <input name="link" type="text" class="form-control" value="{{$card->link}}">

                                              </div>
                                              <div class="modal-footer">
                                                  <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                                                  <button type="submit" class="btn btn-primary">Malumotlarni o'zgartirish</button>
                                              </div>
                                          </form>
                                      </div>

                                  </div>
                              </div>
                          </div>

{{--                          End Update--}}


{{--                          Delete--}}
                          <div class="" >
                              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{$card->id}}" data-bs-whatever="@getbootstrap">Card O'chirish</button>
                          </div>
                          <div class=" modal fade" id="delete{{$card->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                  <div class="modal-content">
                                      <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Card</h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                      </div>
                                      <div class="modal-body">
                                          <form action="{{route('cards.destroy', $card->id)}}" method="post" enctype="multipart/form-data">
                                              @csrf
                                              @method('delete')
                                              <h3>
                                                  Rostan ham malumot o'chirilsimi
                                              </h3>
                                              <div class="modal-footer">
                                                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Rad etish</button>
                                                  <button type="submit" class="btn btn-primary">Ma'lumotni O'chirish</button>
                                              </div>
                                          </form>
                                      </div>

                                  </div>
                              </div>
                          </div>

{{--                          End delete--}}
                      </div>

                   </div>
                   <!--End Icon Box -->



                   @endforeach

               </div>

           </div>

       </div>
   </div>



@endsection