routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    dd('salom');
    $about_left=\App\Models\About_left::find(1);
    $about_right=\App\Models\About_right::find(1);
    $card=\App\Models\Cards::all();
    $contact=\App\Models\Contact::find(1);
    $home=\App\Models\Home::find(1);
    $intro=\App\Models\Introduction::find(1);
    $message=\App\Models\Message::find(1);
    $more=\App\Models\More::all();
    $part=\App\Models\Participants::all();
    $portfolio=DB::select('SELECT p.*,pc.name as category from portfolio p JOIN portfolio_category pc on p.cat_id=pc.id');
    $pricing=\App\Models\Pricing::all();
    $service=\App\Models\Service::all();
    $service_card=\App\Models\Service_card::all();
    $teacher=\App\Models\Teachers::all();

    return view('samo.index.index', compact(

        'about_left', 'about_right','card',
        'contact','home','intro','message','more','part','portfolio',
        'pricing','service','service_card','teacher'

    ));
})->name('samo.home');
Route::get('admin', function () {
    return view('admin.layouts.app');
});
Route::middleware(['auth'])->group(function () {
    Route::resource('about_left',\App\Http\Controllers\About_leftController::class);
    Route::resource('about_right',\App\Http\Controllers\About_rightController::class);
    Route::resource('blog',\App\Http\Controllers\BlogController::class);
    Route::resource('message',\App\Http\Controllers\MessageController::class);
    Route::resource('more',\App\Http\Controllers\MoreController::class);
    Route::resource('portfolio',\App\Http\Controllers\PortfolioController::class);
    Route::resource('pricing',\App\Http\Controllers\PricingController::class);
    Route::resource('cards',\App\Http\Controllers\CardsController::class);
    Route::resource('contact',\App\Http\Controllers\ContactController::class);
    Route::resource('home_main',\App\Http\Controllers\HomeMainController::class);
    Route::resource('introduction',\App\Http\Controllers\IntroductionController::class);
    Route::resource('participants',\App\Http\Controllers\ParticipantsController::class);
    Route::resource('service',\App\Http\Controllers\ServiceController::class);
    Route::resource('service_card',\App\Http\Controllers\Service_cardController::class);
    Route::resource('teachers',\App\Http\Controllers\TeachersController::class);
    Route::resource('count', \App\Http\Controllers\BlogController::class);

});
Route::resource('admin_data', \App\Http\Controllers\About_rightController::class);
Route::resource('sendmessage', \App\Http\Controllers\Message_sendController::class);




Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);



//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home.index');

app/Models/Teachers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Teachers extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'teachers';
    protected $fillable = [

        'id',
        'image',
        'teacher_name',
        'teacher_job',
        'telegram_icon',
        'instagram_icon',
        'facebook_icon',
        'twitter',
    ];
}

app/Http/Controllers/TeachersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use App\Models\Teachers;
use Illuminate\Http\Request;

class TeachersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teachers::all();
        return view('admin.pages.teachers.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'image'=>'required',
            'teacher_name'=>'required',
            'teacher_job'=>'required',
            'telegram_icon'=>'required',
            'instagram_icon'=>'required',
            'facebook_icon'=>'required',
            'twitter'=>'required',


        ]);


        if ($request->file('image')){
            $imageName = time().'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/images/',$imageName);

        }else{
            $imageName='no image';
        }

        Teachers::create([
            'image'=> $imageName,
            'teacher_name'=>$request->teacher_name,
            'teacher_job'=>$request->teacher_job,
            'telegram_icon'=>$request->telegram_icon,
            'instagram_icon'=>$request->instagram_icon,
            'facebook_icon'=>$request->facebook_icon,
            'twitter'=>$request->twitter,


        ]);

        return redirect()->route('teachers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'teacher_name'=>'required',
            'teacher_job'=>'required',
            'telegram_icon'=>'required',
            'instagram_icon'=>'required',
            'facebook_icon'=>'required',
            'twitter'=>'required',



        ]);
        $teachers = Teachers::find($id);
        $teachers->teacher_name = $request->teacher_name;
        $teachers->teacher_job = $request->teacher_job;
        $teachers->telegram_icon = $request->telegram_icon;
        $teachers->instagram_icon = $request->instagram_icon;
        $teachers->facebook_icon = $request->facebook_icon;
        $teachers->twitter = $request->twitter;





        if ($request->file('image')){
            $imageName = time().'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/images/', $imageName);
            if (file_exists(public_path('storage/images/'.$teachers->image))){
                @unlink(public_path('storage/images/'.$teachers->image));
            }
            $teachers->image=$imageName;
        }

        $teachers->update();

        return redirect()->route('teachers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teachers = Teachers::find($id);
        if (file_exists(public_path('storage/images/'.$teachers->image))){
            @unlink(public_path('storage/images/'.$teachers->image));
        }
        $teachers->delete();

        return redirect()->route('teachers.index');
    }
}

resources/views/admin/pages/teachers/index.blade.php
@extends('admin.layouts.app')



@section('main')

    <button type="button" class="btn btn-outline-info col-3 text-center center m-1" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Qo'shish</button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Yaratish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body ">
                    <form action="{{route('teachers.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('post')
                        <div class="mb-3">
                            <label for="image" class="col-form-label">Rasmni kiriting</label>
                            <input name="image" type="file" class="form-control" >

                            <label for="teacher_name" class="col-form-label">Ismni kiriting</label>
                            <input name="teacher_name" type="text" class="form-control" placeholder="ism">

                            <label for="teacher_job" class="col-form-label">kasbni kiriting</label>
                            <input name="teacher_job" type="text" class="form-control" placeholder="kasb">


                            <label for="twitter" class="col-form-label">twitter manzilini kiriting</label>
                            <input name="twitter" type="text" class="form-control" value="https://twitter.com/">


                            <label for="facebook_icon" class="col-form-label">facebook manzilini kiriting</label>
                            <input name="facebook_icon" type="text" class="form-control" value="https://facebook.com/">


                            <label for="instagram_icon" class="col-form-label">instagram manzilini kiriting</label>
                            <input name="instagram_icon" type="text" class="form-control" value="https://instagram.com/">


                            <label for="telegram_icon" class="col-form-label">twitter manzilini kiriting</label>
                            <input name="telegram_icon" type="text" class="form-control" value="https://t.me/">


                        </div>
                        <div class="modal-footer">
                            <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                            <button type="submit" class="btn btn-primary">Yaratish</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>



    <div class="row">
        @foreach($teachers as $item)

            <div class="modal fade" id="exampleModal{{$item->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel{{$item->id}}">Yangi o'zgarish</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{route('teachers.update',$item->id)}}" enctype="multipart/form-data" method="post">
                                @csrf
                                @method('put')

                                <div class="mb-3">
                                    <label for="image" class="col-form-label">Rasmni o'zgartirish</label>
                                    <input name="image" type="file"  class="form-control" value="{{$item->image}}" >

                                    <label for="teacher_name" class="col-form-label">ismni o'zgartirish</label>
                                    <input name="teacher_name" type="text" required class="form-control" value="{{ $item->teacher_name }}">


                                    <label for="teacher_job" class="col-form-label"> kasbni o'zgartirish</label>
                                    <input name="teacher_job" type="text" required class="form-control" value="{{$item->teacher_name}}">

                                    <label for="twitter" class="col-form-label"> twitter linkini o'zgartirish</label>
                                    <input name="twitter" type="text" required class="form-control" value="{{$item->twitter}}">

                                    <label for="facebook_icon" class="col-form-label"> facebook linkini o'zgartirish</label>
                                    <input name="facebook_icon" type="text" required class="form-control" value="{{$item->facebook_icon}}">

                                    <label for="instagram_icon" class="col-form-label"> instagram linkini o'zgartirish</label>
                                    <input name="instagram_icon" type="text" required class="form-control" value="{{$item->instagram_icon}}">

                                    <label for="telegram_icon" class="col-form-label"> telegram linkini o'zgartirish</label>
                                    <input name="telegram_icon" type="text" required class="form-control" value="{{$item->telegram_icon}}">
                                </div>
                                <div class="modal-footer">
                                    <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                                    <button type="submit" class="btn btn-primary">O'zgartirish</button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>


            <div class="col-3">
                <div class="card" style="width: 100%;">
                    <img class="card-img-top" width="300px" height="250px" src="{{ asset('public/storage/images/'.$item->image)  }}" alt="{{$item->image}}">
                    <div class="card-body">
                        <h5 class="card-title">{{$item->teacher_name}}</h5>
                        <p class="card-text">{{$item->teacher_job}}</p>
                        <div class="row w-100 social d-flex justify-content-around float-start">

                            <a class="col-3" href="{{$item->twitter}}"><i class="bi bi-twitter "></i></a>
                            <a class="col-3" href="{{$item->facebook_icon}}"><i class="bi bi-facebook"></i></a>
                            <a class="col-3" href="{{$item->instagram_icon}}"><i class="bi bi-instagram"></i></a>
                            <a class="col-3" href="{{$item->telegram_icon}}"><i class="bi bi-telegram"></i></a>
                        </div>

                        <div class="row col-12 center">
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{$item->id}}" data-bs-whatever="@getbootstrap">O'zgartirish</button>



                            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModaldelete{{$item->id}}" data-bs-whatever="@getbootstrap">O'chirish</button>

                            <div class="modal fade" id="exampleModaldelete{{$item->id}}" tabindex="-1" aria-labelledby="exampleModalLabeldelete" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabeldelete{{$item->id}}">O'chirish</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{route('teachers.destroy',$item->id)}}" enctype="multipart/form-data" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <div class="modal-body">
                                                    <h3>Ishonchingiz komilmi?</h3>
                                                </div>
                                                <div class="modal-footer">
                                                    <button  class="btn btn-secondary " type="button"  data-bs-dismiss="modal" aria-label="Close">Bekor qilish</button>
                                                    <button type="submit" class="btn btn-danger">O'chirish</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


        @endforeach
    </div>



@endsection