routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    dd('salom');
    $about_left=\App\Models\About_left::find(1);
    $about_right=\App\Models\About_right::find(1);
    $card=\App\Models\Cards::all();
    $contact=\App\Models\Contact::find(1);
    $home=\App\Models\Home::find(1);
    $intro=\App\Models\Introduction::find(1);
    $message=\App\Models\Message::find(1);
    $more=\App\Models\More::all();
    $part=\App\Models\Participants::all();
    $portfolio=DB::select('SELECT p.*,pc.name as category from portfolio p JOIN portfolio_category pc on p.cat_id=pc.id');
    $pricing=\App\Models\Pricing::all();
    $service=\App\Models\Service::all();
    $service_card=\App\Models\Service_card::all();
    $teacher=\App\Models\Teachers::all();

    return view('samo.index.index', compact(

        'about_left', 'about_right','card',
        'contact','home','intro','message','more','part','portfolio',
        'pricing','service','service_card','teacher'

    ));
})->name('samo.home');
Route::get('admin', function () {
    return view('admin.layouts.app');
});
Route::middleware(['auth'])->group(function () {
    Route::resource('about_left',\App\Http\Controllers\About_leftController::class);
    Route::resource('about_right',\App\Http\Controllers\About_rightController::class);
    Route::resource('blog',\App\Http\Controllers\BlogController::class);
    Route::resource('message',\App\Http\Controllers\MessageController::class);
    Route::resource('more',\App\Http\Controllers\MoreController::class);
    Route::resource('portfolio',\App\Http\Controllers\PortfolioController::class);
    Route::resource('pricing',\App\Http\Controllers\PricingController::class);
    Route::resource('cards',\App\Http\Controllers\CardsController::class);
    Route::resource('contact',\App\Http\Controllers\ContactController::class);
    Route::resource('home_main',\App\Http\Controllers\HomeMainController::class);
    Route::resource('introduction',\App\Http\Controllers\IntroductionController::class);
    Route::resource('participants',\App\Http\Controllers\ParticipantsController::class);
    Route::resource('service',\App\Http\Controllers\ServiceController::class);
    Route::resource('service_card',\App\Http\Controllers\Service_cardController::class);
    Route::resource('teachers',\App\Http\Controllers\TeachersController::class);
    Route::resource('count', \App\Http\Controllers\BlogController::class);

});
Route::resource('admin_data', \App\Http\Controllers\About_rightController::class);
Route::resource('sendmessage', \App\Http\Controllers\Message_sendController::class);




Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);



//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home.index');

app/Models/Introduction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Introduction extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'intruduction';
    protected $fillable = [

        'id',
        'name',
        'text',
        'video',


    ];
}

app/Http/Controllers/IntroductionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Introduction;
use Illuminate\Http\Request;

class IntroductionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $intro=Introduction::find(1);
        return view('admin.pages.introduction.index', compact('intro'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name'=>'required',
            'text'=>'required',
            'video'=>'required',

        ]);

        $update=Introduction::find($id);
        $update->name=$request->name;
        $update->text=$request->text;
        $update->video=$request->video;





        $update->update();
        return redirect()->route('introduction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/introduction/index.blade.php
    @extends('admin.layouts.app')


@section('main')

        <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <title>Impact Bootstrap Template - Index</title>
        <meta content="" name="description">
        <meta content="" name="keywords">

        <!-- Favicons -->
        <link href="public/samo/assets/img/favicon.png" rel="icon">
        <link href="public/samo/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

        <!-- Vendor CSS Files -->
        <link href="public/samo/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="public/samo/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="public/samo/assets/vendor/aos/aos.css" rel="stylesheet">
        <link href="public/samo/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
        <link href="public/samo/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

        <!-- Template Main CSS File -->
        <link href="public/samo/assets/css/main.css" rel="stylesheet">

        <!-- =======================================================
        * Template Name: Impact - v1.1.1
        * Template URL: https://bootstrapmade.com/impact-bootstrap-business-website-template/
        * Author: BootstrapMade.com
        * License: https://bootstrapmade.com/license/
        ======================================================== -->
    </head>

    <body>


    <div>
        <div class="text-center">
            <section id="call-to-action" class="call-to-action ">
                <div class="container text-center" data-aos="zoom-out">
                    <a href="{{$intro->video}}" class="glightbox play-btn"></a>
                    <h3>{{$intro->name}}</h3>
                    <p> {{$intro->text}}</p>
                    <a class="cta-btn" href="#">Biz bilan aloqa</a>
                </div>
                {{--        Update--}}
                <div class="mt-5">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#update{{$intro->id}}" data-bs-whatever="@getbootstrap">Ma'lumotlarni Tahrirlash</button>
                </div>
                <div class="modal fade" id="update{{$intro->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Ma'lumotlarni Tahrirlash</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="{{route('introduction.update', $intro->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('put')
                                    <div class="mb-3">

                                        <label for="name" class="form-label">Asosiy yozuv</label>
                                        <input type="text" name="name" class="form-control" value="{{$intro->name}}">

                                        <label for="name" class="form-label">Oddiy yozuv</label>
                                        <input type="text" name="text" class="form-control" value="{{$intro->text}}">

                                        <label for="name" class="form-label">Video link</label>
                                        <input type="text" name="video" class="form-control" value="{{$intro->video}}">

                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                                        <button type="submit" class="btn btn-primary">Malumotlarni o'zgartirish</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>

                {{--                          End Update--}}
            </section><!-- End Call To Action Section -->

        </div>


    </div>




    <!-- Vendor JS Files -->
    <script src="public/samo/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="public/samo/assets/vendor/aos/aos.js"></script>
    <script src="public/samo/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="public/samo/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="public/samo/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="public/samo/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="public/samo/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="public/samo/assets/js/main.js"></script>
    </body>

</html>


@endsection