routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    dd('salom');
    $about_left=\App\Models\About_left::find(1);
    $about_right=\App\Models\About_right::find(1);
    $card=\App\Models\Cards::all();
    $contact=\App\Models\Contact::find(1);
    $home=\App\Models\Home::find(1);
    $intro=\App\Models\Introduction::find(1);
    $message=\App\Models\Message::find(1);
    $more=\App\Models\More::all();
    $part=\App\Models\Participants::all();
    $portfolio=DB::select('SELECT p.*,pc.name as category from portfolio p JOIN portfolio_category pc on p.cat_id=pc.id');
    $pricing=\App\Models\Pricing::all();
    $service=\App\Models\Service::all();
    $service_card=\App\Models\Service_card::all();
    $teacher=\App\Models\Teachers::all();

    return view('samo.index.index', compact(

        'about_left', 'about_right','card',
        'contact','home','intro','message','more','part','portfolio',
        'pricing','service','service_card','teacher'

    ));
})->name('samo.home');
Route::get('admin', function () {
    return view('admin.layouts.app');
});
Route::middleware(['auth'])->group(function () {
    Route::resource('about_left',\App\Http\Controllers\About_leftController::class);
    Route::resource('about_right',\App\Http\Controllers\About_rightController::class);
    Route::resource('blog',\App\Http\Controllers\BlogController::class);
    Route::resource('message',\App\Http\Controllers\MessageController::class);
    Route::resource('more',\App\Http\Controllers\MoreController::class);
    Route::resource('portfolio',\App\Http\Controllers\PortfolioController::class);
    Route::resource('pricing',\App\Http\Controllers\PricingController::class);
    Route::resource('cards',\App\Http\Controllers\CardsController::class);
    Route::resource('contact',\App\Http\Controllers\ContactController::class);
    Route::resource('home_main',\App\Http\Controllers\HomeMainController::class);
    Route::resource('introduction',\App\Http\Controllers\IntroductionController::class);
    Route::resource('participants',\App\Http\Controllers\ParticipantsController::class);
    Route::resource('service',\App\Http\Controllers\ServiceController::class);
    Route::resource('service_card',\App\Http\Controllers\Service_cardController::class);
    Route::resource('teachers',\App\Http\Controllers\TeachersController::class);
    Route::resource('count', \App\Http\Controllers\BlogController::class);

});
Route::resource('admin_data', \App\Http\Controllers\About_rightController::class);
Route::resource('sendmessage', \App\Http\Controllers\Message_sendController::class);




Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);



//Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home.index');

app/Models/More.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class More extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'more';
    protected $fillable = [

        'id',
        'name',
        'swipe_text',



    ];
}

app/Http/Controllers/MoreController.php
<?php

namespace App\Http\Controllers;

use App\Models\More;

use App\Models\Participants;
use Illuminate\Http\Request;

class MoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $more = More::all();
        return view('admin.pages.more.index', compact('more'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name'=>'required',
            'swipe_text'=>'required',



        ]);

        More::create([
            'name'=> $request->name,
            'swipe_text'=>$request->swipe_text,

        ]);

        return redirect()->route('more.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name'=>'required',
            'swipe_text'=>'required',


        ]);
        $more = More::find($id);
        $more->name = $request->name;
        $more->swipe_text = $request->swipe_text;

        $more->update();

        return redirect()->route('more.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $more = More::find($id);
        $more->delete();

        return redirect()->route('more.index');
    }
}

resources/views/admin/pages/more/index.blade.php
@extends('admin.layouts.app')



@section('main')


<div class="container">
    <div class="text-center">Qo'shimcha Savollar</div>
    <button type="button" class="btn btn-outline-info col-3 text-center center m-1" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Qo'shish</button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Qo'shish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body ">
                    <form action="{{route('more.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('post')
                        <div class="mb-3">


                            <label for="name" class="col-form-label">savolni kiriting</label>
                            <input name="name" type="text" class="form-control" placeholder="savol">

                            <label for="swipe_text" class="col-form-label">javobni kiriting</label>
                            <input name="swipe_text" type="text" class="form-control" placeholder="javob">





                        </div>
                        <div class="modal-footer">
                            <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                            <button type="submit" class="btn btn-primary">Yaratish</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="row">
       @foreach($more as $item)
            <div class="modal fade" id="exampleModal{{$item->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel{{$item->id}}">Yangi o'zgarish</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{route('more.update',$item->id)}}" enctype="multipart/form-data" method="post">
                                @csrf
                                @method('put')

                                <div class="mb-3">
                                    <label for="name" class="col-form-label">savolni o'zgartirish</label>
                                    <input name="name" type="text"  class="form-control" value="{{$item->name}}" >

                                    <label for="swipe_text" class="col-form-label">javobni o'zgartirish</label>
                                    <input name="swipe_text" type="text" required class="form-control" value="{{ $item->swipe_text }}">



                                </div>
                                <div class="modal-footer">
                                    <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                                    <button type="submit" class="btn btn-primary">O'zgartirish</button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h3 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-1{{$item->id}}">

                        {{$item->name}}
                    </button>
                </h3>
                <div id="faq-content-1{{$item->id}}" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                    <div class="accordion-body">
                        {{$item->swipe_text}}
                        <div class="row">
                            <button  type="button" class="btn btn-primary col-3" data-bs-toggle="modal" data-bs-target="#exampleModal{{$item->id}}" data-bs-whatever="@getbootstrap">O'zgartirish</button>

                            <div class="modal fade" id="exampleModal{{$item->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{$item->id}}">Yangi o'zgarish</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{route('more.update',$item->id)}}" enctype="multipart/form-data" method="post">
                                                @csrf
                                                @method('put')

                                                <div class="mb-3">
                                                    <label for="name" class="col-form-label">savolni o'zgartirish</label>
                                                    <input name="name" type="text"  class="form-control" value="{{$item->name}}" >

                                                    <label for="swipe_text" class="col-form-label">javobni o'zgartirish</label>
                                                    <input name="swipe_text" type="text" required class="form-control" value="{{ $item->swipe_text }}">



                                                </div>
                                                <div class="modal-footer">
                                                    <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                                                    <button type="submit" class="btn btn-primary">O'zgartirish</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>


                            <button type="button" class="btn btn-outline-danger col-3" data-bs-toggle="modal" data-bs-target="#exampleModal{{$item->name}}" data-bs-whatever="@getbootstrap">O'chirish</button>

                            <div class="modal fade" id="exampleModal{{$item->name}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{$item->id+1}}">O'chirish</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{route('more.destroy',$item->id)}}" enctype="multipart/form-data" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <div class="modal-body">
                                                    <h3>Ishonchingiz komilmi?</h3>
                                                </div>
                                                <div class="modal-footer">
                                                    <button  class="btn btn-secondary" data-bs-dismiss="modal">Bekor qilish</button>
                                                    <button type="submit" class="btn btn-danger">O'chirish</button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div><!-- # Faq item-->

        @endforeach

    </div>
</div>


    @endsection